version = 1

test_patterns = [
  "**/*/*_test.go",
  "**/*/mock.go"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/scmmishra/slick-deploy"

[[transformers]]
name = "gofmt"